{% set name = "starlite-sessions" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/starlite-sessions-{{ version }}.tar.gz
  sha256: 9f309a2f9da82e78dbc5142ae56084d7df44aab6d0de4cea1aceef411df806d7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - cryptography
    - python >=3.6,<4.0
    - starlite >=1.17.1

test:
  imports:
    - starlite_sessions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/starlite-api/starlite-sessions
  doc_url: https://starlite-api.github.io/starlite-sessions/
  summary: Starlite Sessions Toolkit
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
